FROM ad-vcpkg:latest

WORKDIR /home/trtuser

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

#####################
# ncnn
#####################
RUN git clone https://github.com/Tencent/ncnn.git && \
    cd ncnn && \
    git submodule update --init && \
    mkdir -p build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_SYSTEM_GLSLANG=ON -DNCNN_BUILD_EXAMPLES=ON .. && \
    make -j "$(nproc)" && \
    sudo make install
